# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extractGeneStateFromTimeSeriesCube <- function(timeSeriesCube, temporal) {
    .Call(`_FBNNet_extractGeneStateFromTimeSeriesCube`, timeSeriesCube, temporal)
}

extractGeneStates <- function(stateMatrix, targetgenes) {
    .Call(`_FBNNet_extractGeneStates`, stateMatrix, targetgenes)
}

generateTemporalGeneStates <- function(mainParameters, targetgene, conditional_genes, temporal) {
    .Call(`_FBNNet_generateTemporalGeneStates`, mainParameters, targetgene, conditional_genes, temporal)
}

getBasicMeasures <- function(stateTCond, m, mc, cond_T_target_T_state, cond_F_target_T_state, cond_T_target_F_state, cond_F_target_F_state, cond_T_target_T_state_c, cond_F_target_T_state_c, cond_T_target_F_state_c, cond_F_target_F_state_c, recount_target) {
    .Call(`_FBNNet_getBasicMeasures`, stateTCond, m, mc, cond_T_target_T_state, cond_F_target_T_state, cond_T_target_F_state, cond_F_target_F_state, cond_T_target_T_state_c, cond_F_target_T_state_c, cond_T_target_F_state_c, cond_F_target_F_state_c, recount_target)
}

getGenePrababilities_basic <- function(main_parameters_in_ref, fixedgenestate, target_gene, new_conditional_gene, temporal, targetCounts) {
    .Call(`_FBNNet_getGenePrababilities_basic`, main_parameters_in_ref, fixedgenestate, target_gene, new_conditional_gene, temporal, targetCounts)
}

getAdvancedMeasures <- function(basic_measures) {
    .Call(`_FBNNet_getAdvancedMeasures`, basic_measures)
}

getGenePrababilities_advanced <- function(getGenePrababilities_basic) {
    .Call(`_FBNNet_getGenePrababilities_advanced`, getGenePrababilities_basic)
}

getGenePrababilities <- function(main_parameters_in_ref, fixedgenestate, target_gene, new_conditional_gene, temporal, targetCounts) {
    .Call(`_FBNNet_getGenePrababilities`, main_parameters_in_ref, fixedgenestate, target_gene, new_conditional_gene, temporal, targetCounts)
}

networkFiltering <- function(res) {
    .Call(`_FBNNet_networkFiltering`, res)
}

filterTargetGenesByConditionGenes <- function(targetGenes, mainParameters, genes, matchedgenes, temporal = 1L, targetCounts = NULL) {
    .Call(`_FBNNet_filterTargetGenesByConditionGenes`, targetGenes, mainParameters, genes, matchedgenes, temporal, targetCounts)
}

getGenePrababilities_measurements <- function(targetGene, mainParameters, genes, matchedgenes, temporal = 1L, targetCounts = NULL) {
    .Call(`_FBNNet_getGenePrababilities_measurements`, targetGene, mainParameters, genes, matchedgenes, temporal, targetCounts)
}

buildProbabilityTreeOnTargetGene <- function(targetGene, mainParameters, genes, matchedgenes, matchedexpression, maxK = 4L, temporal = 1L, targetCounts = NULL, findPositiveRegulate = FALSE, findNegativeRegulate = FALSE) {
    .Call(`_FBNNet_buildProbabilityTreeOnTargetGene`, targetGene, mainParameters, genes, matchedgenes, matchedexpression, maxK, temporal, targetCounts, findPositiveRegulate, findNegativeRegulate)
}

mineNetworksDirect <- function(targetGene, mainParameters, genes, matchedgenes, matchedexpression, maxK = 4L, temporal = 1L, targetCounts = NULL, findPositiveRegulate = FALSE, findNegativeRegulate = FALSE) {
    .Call(`_FBNNet_mineNetworksDirect`, targetGene, mainParameters, genes, matchedgenes, matchedexpression, maxK, temporal, targetCounts, findPositiveRegulate, findNegativeRegulate)
}

internalloopByWhole2 <- function(target_gene, conditional_genes, maxK, temporal, mainParameters) {
    .Call(`_FBNNet_internalloopByWhole2`, target_gene, conditional_genes, maxK, temporal, mainParameters)
}

to_string <- function(val) {
    .Call(`_FBNNet_to_string`, val)
}

mpaste <- function(x, sep) {
    .Call(`_FBNNet_mpaste`, x, sep)
}

concatenator <- function(a, b) {
    .Call(`_FBNNet_concatenator`, a, b)
}

concatenatorI <- function(a, b) {
    .Call(`_FBNNet_concatenatorI`, a, b)
}

concatenatorN <- function(a, b) {
    .Call(`_FBNNet_concatenatorN`, a, b)
}

mcbind <- function(a, b) {
    .Call(`_FBNNet_mcbind`, a, b)
}

mrbind <- function(a, b) {
    .Call(`_FBNNet_mrbind`, a, b)
}

isReallyNA <- function(val) {
    .Call(`_FBNNet_isReallyNA`, val)
}

countZeros <- function(v) {
    .Call(`_FBNNet_countZeros`, v)
}

#' @title Accessing R's fisher.test function from Rcpp
fisher_test_cpp <- function(x, conf_level) {
    .Call(`_FBNNet_fisher_test_cpp`, x, conf_level)
}

substractM <- function(m, v) {
    .Call(`_FBNNet_substractM`, m, v)
}

matchCount <- function(m, v) {
    .Call(`_FBNNet_matchCount`, m, v)
}

dround <- function(val, decimal) {
    .Call(`_FBNNet_dround`, val, decimal)
}

a_in_b <- function(names1, names2) {
    .Call(`_FBNNet_a_in_b`, names1, names2)
}

a_in_b_index <- function(names1, names2) {
    .Call(`_FBNNet_a_in_b_index`, names1, names2)
}

a_not_in_b <- function(names1, names2) {
    .Call(`_FBNNet_a_not_in_b`, names1, names2)
}

a_not_in_b_index <- function(names1, names2) {
    .Call(`_FBNNet_a_not_in_b_index`, names1, names2)
}

resizel <- function(x, n) {
    .Call(`_FBNNet_resizel`, x, n)
}

orderByname <- function(x, names) {
    .Call(`_FBNNet_orderByname`, x, names)
}

removeEmptyElement <- function(x) {
    .Call(`_FBNNet_removeEmptyElement`, x)
}

char_sort <- function(x, dsc) {
    .Call(`_FBNNet_char_sort`, x, dsc)
}

int_sort <- function(x, dsc) {
    .Call(`_FBNNet_int_sort`, x, dsc)
}

num_sort <- function(x, dsc) {
    .Call(`_FBNNet_num_sort`, x, dsc)
}

convertStringIntoVector <- function(value, outputType, lowerCase) {
    .Call(`_FBNNet_convertStringIntoVector`, value, outputType, lowerCase)
}

subCPP <- function(pattern, replacement, x) {
    .Call(`_FBNNet_subCPP`, pattern, replacement, x)
}

splitExpression <- function(expression, outputType, lowerCase) {
    .Call(`_FBNNet_splitExpression`, expression, outputType, lowerCase)
}

