# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A function that extract gene states from time series cube
#' @param timeSeriesCube The time series cube
#' @param temporal The temporal time step
extractGeneStateFromTimeSeriesCube <- function(timeSeriesCube, temporal) {
    .Call(`_FBNNet_extractGeneStateFromTimeSeriesCube`, timeSeriesCube, temporal)
}

#' A function to get gene probabilities
#' @param main_parameters_in_ref An environment variable to hold all input data.
#' @param fixedgenestate A list of pre-processed gene state.
#' @param target_gene The target gene
#' @param new_conditional_gene The new conditional gene to be added in.
#' @param temporal The temporal time step.
#' @param targetCounts The count of the target count.
getGenePrababilities_basic <- function(main_parameters_in_ref, fixedgenestate, target_gene, new_conditional_gene, temporal, targetCounts) {
    .Call(`_FBNNet_getGenePrababilities_basic`, main_parameters_in_ref, fixedgenestate, target_gene, new_conditional_gene, temporal, targetCounts)
}

#' The main function to main FBN probabilities from time series data
#' 
#' @param getGenePrababilities_basic The basic calculations.
getGenePrababilities_advanced <- function(getGenePrababilities_basic) {
    .Call(`_FBNNet_getGenePrababilities_advanced`, getGenePrababilities_basic)
}

#' The main function to main FBN probabilities from time series data
#' 
#' @param main_parameters_in_ref The environment that contains the required data.
#' @param fixedgenestate The up stream fixed gene state.
#' @param target_gene The target gene.
#' @param new_conditional_gene The current stream conditional gene.
#' @param temporal The temporal time step.
#' @param targetCounts A list of pre-calculated targe genes.
getGenePrababilities <- function(main_parameters_in_ref, fixedgenestate, target_gene, new_conditional_gene, temporal, targetCounts) {
    .Call(`_FBNNet_getGenePrababilities`, main_parameters_in_ref, fixedgenestate, target_gene, new_conditional_gene, temporal, targetCounts)
}

#' A function to filter networks.
#' 
#' @param res A list of named network interactions
networkFiltering <- function(res) {
    .Call(`_FBNNet_networkFiltering`, res)
}

#' Get the main measurements based on the input data
#' 
#' @param targetGene The target gene
#' @param mainParameters An environment variable holds all input data
#' @param genes All conditional genes
#' @param matchedgenes processed genes
#' @param temporal The temporal time steps
#' @param targetCounts  Counts the number of target gene in the data
#' 
getGenePrababilities_measurements <- function(targetGene, mainParameters, genes, matchedgenes, temporal = 1L, targetCounts = NULL) {
    .Call(`_FBNNet_getGenePrababilities_measurements`, targetGene, mainParameters, genes, matchedgenes, temporal, targetCounts)
}

#' build Probability Tree On the targetGene
#' 
#' @param targetGene The target gene
#' @param mainParameters An environment variable holds all input data
#' @param genes All conditional genes
#' @param matchedgenes processed genes
#' @param matchedexpression matched the expression of an interaction 
#' @param maxK The maximum level that can be drilled in.
#' @param temporal The temporal time steps
#' @param targetCounts  Counts the number of target gene in the data
#' @param findPositiveRegulate Optional if TRUE find positive regulation only
#' @param findNegativeRegulate Optional if TRUE find negative regulation only
buildProbabilityTreeOnTargetGene <- function(targetGene, mainParameters, genes, matchedgenes, matchedexpression, maxK = 4L, temporal = 1L, targetCounts = NULL, findPositiveRegulate = FALSE, findNegativeRegulate = FALSE) {
    .Call(`_FBNNet_buildProbabilityTreeOnTargetGene`, targetGene, mainParameters, genes, matchedgenes, matchedexpression, maxK, temporal, targetCounts, findPositiveRegulate, findNegativeRegulate)
}

#' Get the main measurements based on the input data
#' 
#' @param target_gene The target gene
#' @param conditional_genes conditional genes
#' @param maxK The maximum under ground levels
#' @param temporal The temporal time steps
#' @param mainParameters An environment variable holds all input data
#' 
process_cube_algorithm <- function(target_gene, conditional_genes, maxK, temporal, mainParameters) {
    .Call(`_FBNNet_process_cube_algorithm`, target_gene, conditional_genes, maxK, temporal, mainParameters)
}

#' A function concate a vector with a sperator
#' @param x The vector
#' @param sep Seperator
#' @return A new string
NULL

#' A function to split an expression into a vector of input
#' 
#' @param expression The expression fo a FBN network connection
#' @param outputType The type of output.
#' @param lowerCase Optional, if TRUE convert them to lower case.
splitExpression <- function(expression, outputType, lowerCase) {
    .Call(`_FBNNet_splitExpression`, expression, outputType, lowerCase)
}

